### ISSUE TITLE
Instructions for hackathon members to access excel models

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/solutions#294]
Request: A document that describes for contributors how to import a model. 

Not all models are fully public. We need confirmation from Chad and/ or Mamta of what we can expose and how. 

Background: There wasn't a clean clear way how to do this during the last hackathon. Improve upon that process.

**Comment by Sunishchal** [comment]
There is an [NDA](https://drive.google.com/file/d/1KISsmtDULJ_GGAEAKAPRwqEaILY0awED/view?usp=sharing) that all attendees must sign before gaining access to the Excel models. We will give access only to the workbooks relevant to the task(s) each attendee is working on. 

Will work on a video once the contributing & setup guidelines are updated. Will also commission @ksatan & Casper's help to put together a document with a gentle introduction to the Drawdown terminology & high level methodology.

**Comment by colleenskemp** [comment]
Discussed with Chad and he has confirmed the above.

We cannot release all the models on github. They have proprietary data. The NDA is a great solution. 

What the participants need is access to specific excels. We need a directory that has the excel in it to that those who have signed an NDA. 

Next step: Make a special one for the hackathon users.  This should include all the spreadsheets that the hackathon participants need.

**Comment by denised** [comment]
An additional note:  I have found it to be essential to be able to look at multiple models at the same time --- the one I am working on, and one that has already been successfully converted.  This allows me to see what the code is supposed to do, and to tell if the weirdness I am looking at is because of the code or the model.   So our setup needs to make available multiple models to all participants.  I would vote for having a couple of models (one RSS model, one LAND model) visible to all participants, since that will also help with education and cross-team collaboration.

**Comment by denised** [comment]
I believe we're done with this :-)
