### ISSUE TITLE
Bug "unknown adoption name" when trying to instantiate scenario

### ISSUE THREAD

**Issue by denised** [ProjectDrawdown/solutions#307]
I have yet to get tests to pass for residential glass, but the first few scenarios I've tried loading were able to load.
One scenario, 'PDS2-100p2050-based on a 5% retrofit rate', did not load, and resulted in the following error:
```
C:\Working\solutions\solution\residentialglass\__init__.py in __init__(self, scenario)
    241             pass
    242         elif self.ac.soln_pds_adoption_basis == 'Fully Customized PDS':
--> 243             pds_adoption_data_per_region = self.pds_ca.adoption_data_per_region()
    244             pds_adoption_trend_per_region = self.pds_ca.adoption_trend_per_region()
    245             pds_adoption_is_single_source = None

C:\Working\solutions\model\customadoption.py in adoption_data_per_region(self)
    274             result = data['df'].copy()
    275         else:
--> 276             raise ValueError('Unknown adoption name: ' + str(self.soln_adoption_custom_name))
    277         if self.total_adoption_limit is not None:
    278             idx = self.total_adoption_limit.first_valid_index()

ValueError: Unknown adoption name: 40% Adoption in 2014, 5.0% building stock retrofit rate
```

The code appears to be looking for a custom adoption by that name in the `ca_pds_data` directory, and indeed there is not one.
I'm opening this ticket to remember to work on it later, and in case others run into similar errors.

**Comment by babablacksheep** [comment]
In case it helps, this bug also comes up with the commercial glass solution, with several scenarios including

- `PDS1-57p2050-based on a 2.75% retrofit rate`
- `PDS3-60p2050-based on an 8% retrofit rate (Integrated)`

It does not happen for

- `PDS2-95p2050-Based on 5% Retrofit Rate`

**Comment by babablacksheep** [comment]
Here's what I've found so far. This is based on investigating the bug for the commercial glass solution, but I think it would also apply to the residential glass solution bug.

When the scenario is being loaded it tries to load a csv file from the `ca_pads_data` folder. It determines the name of this csv file from the json property `soln_pds_adoption_custom_name`.

Therefore to fix the bug `soln_pds_adoption_custom_name` needs to point to a valid csv file in the `ca_pads_data` folder. 

This string is basically taken from Excel sheet 'Scenario Record' in the section "Fully Customized PDS", from the row "Scenario Name".

So I think there should be some logic somewhere in solution_xls_extract.py that parses that name correctly and only takes the `8.0% building stock retrofit rate` if the string is something like `40% Adoption in 2014, 8.0% building stock retrofit rate`. Because the csv file names in the `ca_pads_data` all do not mention the adoption percentage in their names. 

In order to proceed with #270 we're just going to edit the scenario json files accordingly. But hopefully this helps someone more familiar with solution_xls_extract.py to add some custom parsing to handle strings like `40% Adoption in 2014, 8.0% building stock retrofit rate`

**Comment by babablacksheep** [comment]
I should also mention, that when I try to run a scenario such as `40% Adoption in 2014, 2.75% building stock retrofit rate
` in Excel and if I look at the `Custom PDS Adoption` sheet, it uses the scenario factoring table for "Scenario 1 - 2.75% building stock retrofit". 

So I don't think it is a case that there is a missing csv file in the `ca_pds_data` folder. There are three scenario factoring tables in the Excel sheet, and they are all written out to the `ca_pds_data` folder.

**Comment by denised** [comment]
Great notes @babablacksheep --- thank you!

**Comment by denised** [comment]
This is probably fixed.  Fix is in hackathon branch for now.

**Comment by denised** [comment]
The fix above does work, however on further investigation, it is the Excel that is wrong.  Most likely the failing scenario named an Adoption that previously existed but was later removed.  Defaulting to some other behavior may work, but isn't in any real sense correct.  So we are electing **not** to bring this behavior into the develop branch.

Instead, we expect to resolve this issue by cleaning out the old/bad scenarios  (Issue #376).
